apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: dev
data:
  REDIS_HOST: {{ .Values.backendConfig.REDIS_HOST | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.backendConfig.AWS_ACCESS_KEY_ID | quote  }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.backendConfig.AWS_SECRET_ACCESS_KEY | quote  }}
  AWS_REGION: {{ .Values.backendConfig.AWS_REGION | quote  }}