apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  namespace: dev
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: your-registry/backend:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: backend-config  # Reference the ConfigMap for the backend
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
